version: '3'

services:
  db:
    container_name: postgres
    hostname: postgres
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
  web:
    restart: always
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: /usr/local/bin/gunicorn eventticketingserver.wsgi:application -w 2 -b :8000 --reload
