# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-16 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='customer_id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='event_id', primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('event_name', models.CharField(max_length=200)),
                ('event_organizer', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='location_id', primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='ticket_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ticket_type', models.CharField(max_length=200)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('quota', models.BigIntegerField(blank=True, default=0, null=True)),
                ('event', models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apiv1.Event')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='TicketTransaction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='ticket_transaction_id', primary_key=True, serialize=False)),
                ('quatity', models.IntegerField(default=0)),
                ('total_price', models.BigIntegerField(blank=True, null=True)),
                ('ticket', models.ForeignKey(blank=True, db_column='ticket_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apiv1.Ticket')),
            ],
            options={
                'db_table': 'ticket_transaction',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='transaction_id', primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(default=0)),
                ('payment_method', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apiv1.Customer')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.AddField(
            model_name='tickettransaction',
            name='transaction',
            field=models.ForeignKey(blank=True, db_column='transaction_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apiv1.Transaction'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apiv1.Location'),
        ),
    ]
