# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-17 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(blank=True, db_column='event_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='apiv1.Event'),
        ),
    ]
