# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-18 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_auto_20180717_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tickettransaction',
            name='transaction',
            field=models.ForeignKey(blank=True, db_column='transaction_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_transaction', to='apiv1.Transaction'),
        ),
    ]
